// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  DeleteApiV1RolesByIdData,
  DeleteApiV1RolesByIdErrors,
  DeleteApiV1RolesByIdResponses,
  DeleteApiV1UsersByIdData,
  DeleteApiV1UsersByIdErrors,
  DeleteApiV1UsersByIdResponses,
  GetApiV1AuthenticationCheckData,
  GetApiV1AuthenticationCheckErrors,
  GetApiV1AuthenticationCheckResponses,
  GetApiV1AuthenticationMeData,
  GetApiV1AuthenticationMeErrors,
  GetApiV1AuthenticationMeResponses,
  GetApiV1AuthenticationMfaTotpEnableData,
  GetApiV1AuthenticationMfaTotpEnableErrors,
  GetApiV1AuthenticationMfaTotpEnableResponses,
  GetApiV1RolesByIdData,
  GetApiV1RolesByIdErrors,
  GetApiV1RolesByIdResponses,
  GetApiV1RolesData,
  GetApiV1RolesErrors,
  GetApiV1RolesResponses,
  GetApiV1UsersByIdData,
  GetApiV1UsersByIdErrors,
  GetApiV1UsersByIdResponses,
  GetApiV1UsersByUserIdListRolesData,
  GetApiV1UsersByUserIdListRolesErrors,
  GetApiV1UsersByUserIdListRolesResponses,
  GetApiV1UsersData,
  GetApiV1UsersErrors,
  GetApiV1UsersResponses,
  PostApiV1AuthenticationLogoutData,
  PostApiV1AuthenticationLogoutErrors,
  PostApiV1AuthenticationLogoutResponses,
  PostApiV1AuthenticationMfaTotpResetByIdData,
  PostApiV1AuthenticationMfaTotpResetByIdErrors,
  PostApiV1AuthenticationMfaTotpResetByIdResponses,
  PostApiV1AuthenticationMfaTotpVerifyData,
  PostApiV1AuthenticationMfaTotpVerifyErrors,
  PostApiV1AuthenticationMfaTotpVerifyResponses,
  PostApiV1RolesData,
  PostApiV1RolesErrors,
  PostApiV1RolesResponses,
  PostApiV1UsersAssignRoleByUserIdByRoleIdData,
  PostApiV1UsersAssignRoleByUserIdByRoleIdErrors,
  PostApiV1UsersAssignRoleByUserIdByRoleIdResponses,
  PostApiV1UsersData,
  PostApiV1UsersErrors,
  PostApiV1UsersResponses,
  PostApiV1UsersUnassignRoleByUserIdByRoleIdData,
  PostApiV1UsersUnassignRoleByUserIdByRoleIdErrors,
  PostApiV1UsersUnassignRoleByUserIdByRoleIdResponses,
  PutApiV1RolesByIdData,
  PutApiV1RolesByIdErrors,
  PutApiV1RolesByIdResponses,
  PutApiV1UsersByIdData,
  PutApiV1UsersByIdErrors,
  PutApiV1UsersByIdResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Check Authentication Status
 *
 * Checks if a user is authenticated.
 */
export const getApiV1AuthenticationCheck = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetApiV1AuthenticationCheckData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetApiV1AuthenticationCheckResponses,
    GetApiV1AuthenticationCheckErrors,
    ThrowOnError
  >({
    url: '/api/v1/authentication/check',
    ...options,
  });
};

/**
 * Logout User
 *
 * Logs out the authenticated user.
 */
export const postApiV1AuthenticationLogout = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PostApiV1AuthenticationLogoutData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    PostApiV1AuthenticationLogoutResponses,
    PostApiV1AuthenticationLogoutErrors,
    ThrowOnError
  >({
    url: '/api/v1/authentication/logout',
    ...options,
  });
};

/**
 * Get Current User
 *
 * Returns the current user's information.
 */
export const getApiV1AuthenticationMe = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1AuthenticationMeData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetApiV1AuthenticationMeResponses,
    GetApiV1AuthenticationMeErrors,
    ThrowOnError
  >({
    url: '/api/v1/authentication/me',
    ...options,
  });
};

/**
 * Enable TOTP MFA
 *
 * Enables Time-based One-Time Password (TOTP) Multi-Factor Authentication for the user.
 */
export const getApiV1AuthenticationMfaTotpEnable = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetApiV1AuthenticationMfaTotpEnableData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetApiV1AuthenticationMfaTotpEnableResponses,
    GetApiV1AuthenticationMfaTotpEnableErrors,
    ThrowOnError
  >({
    url: '/api/v1/authentication/mfa/totp/enable',
    ...options,
  });
};

/**
 * Reset TOTP MFA
 *
 * Resets the Time-based One-Time Password (TOTP) Multi-Factor Authentication for the user.
 */
export const postApiV1AuthenticationMfaTotpResetById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiV1AuthenticationMfaTotpResetByIdData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    PostApiV1AuthenticationMfaTotpResetByIdResponses,
    PostApiV1AuthenticationMfaTotpResetByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/authentication/mfa/totp/reset/{id}',
    ...options,
  });
};

/**
 * Verify TOTP MFA
 *
 * Verifies the Time-based One-Time Password (TOTP) Multi-Factor Authentication code for the user.
 */
export const postApiV1AuthenticationMfaTotpVerify = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<PostApiV1AuthenticationMfaTotpVerifyData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    PostApiV1AuthenticationMfaTotpVerifyResponses,
    PostApiV1AuthenticationMfaTotpVerifyErrors,
    ThrowOnError
  >({
    url: '/api/v1/authentication/mfa/totp/verify',
    ...options,
  });
};

/**
 * Get Roles
 *
 * This endpoint retrieves all roles.
 */
export const getApiV1Roles = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1RolesData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetApiV1RolesResponses,
    GetApiV1RolesErrors,
    ThrowOnError
  >({
    url: '/api/v1/roles',
    ...options,
  });
};

/**
 * Create Role
 *
 * This endpoint creates a new role.
 */
export const postApiV1Roles = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1RolesData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    PostApiV1RolesResponses,
    PostApiV1RolesErrors,
    ThrowOnError
  >({
    url: '/api/v1/roles',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete Role
 *
 * This endpoint deletes an existing role by their id.
 */
export const deleteApiV1RolesById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1RolesByIdData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteApiV1RolesByIdResponses,
    DeleteApiV1RolesByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/roles/{id}',
    ...options,
  });
};

/**
 * Get Role
 *
 * This endpoint retrieves an existing role by their id.
 */
export const getApiV1RolesById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1RolesByIdData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    GetApiV1RolesByIdResponses,
    GetApiV1RolesByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/roles/{id}',
    ...options,
  });
};

/**
 * Update Role
 *
 * This endpoint updates an existing role by their id.
 */
export const putApiV1RolesById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1RolesByIdData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    PutApiV1RolesByIdResponses,
    PutApiV1RolesByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/roles/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get Users
 *
 * This endpoint retrieves all users.
 */
export const getApiV1Users = <ThrowOnError extends boolean = false>(
  options?: Options<GetApiV1UsersData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetApiV1UsersResponses,
    GetApiV1UsersErrors,
    ThrowOnError
  >({
    url: '/api/v1/users',
    ...options,
  });
};

/**
 * Create User
 *
 * This endpoint creates a new user.
 */
export const postApiV1Users = <ThrowOnError extends boolean = false>(
  options: Options<PostApiV1UsersData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    PostApiV1UsersResponses,
    PostApiV1UsersErrors,
    ThrowOnError
  >({
    url: '/api/v1/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Assign Role
 *
 * This endpoint assigns a role to a user
 */
export const postApiV1UsersAssignRoleByUserIdByRoleId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiV1UsersAssignRoleByUserIdByRoleIdData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    PostApiV1UsersAssignRoleByUserIdByRoleIdResponses,
    PostApiV1UsersAssignRoleByUserIdByRoleIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/users/assign-role/{userId}/{roleId}',
    ...options,
  });
};

/**
 * Unassign Role
 *
 * This endpoint unassigns a role from a user
 */
export const postApiV1UsersUnassignRoleByUserIdByRoleId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostApiV1UsersUnassignRoleByUserIdByRoleIdData, ThrowOnError>
) => {
  return (options.client ?? client).post<
    PostApiV1UsersUnassignRoleByUserIdByRoleIdResponses,
    PostApiV1UsersUnassignRoleByUserIdByRoleIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/users/unassign-role/{userId}/{roleId}',
    ...options,
  });
};

/**
 * Delete User
 *
 * This endpoint deletes an existing user by their id.
 */
export const deleteApiV1UsersById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteApiV1UsersByIdData, ThrowOnError>
) => {
  return (options.client ?? client).delete<
    DeleteApiV1UsersByIdResponses,
    DeleteApiV1UsersByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/users/{id}',
    ...options,
  });
};

/**
 * Get User
 *
 * This endpoint retrieves an existing user by their id.
 */
export const getApiV1UsersById = <ThrowOnError extends boolean = false>(
  options: Options<GetApiV1UsersByIdData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    GetApiV1UsersByIdResponses,
    GetApiV1UsersByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/users/{id}',
    ...options,
  });
};

/**
 * Update User
 *
 * This endpoint updates an existing user by their id.
 */
export const putApiV1UsersById = <ThrowOnError extends boolean = false>(
  options: Options<PutApiV1UsersByIdData, ThrowOnError>
) => {
  return (options.client ?? client).put<
    PutApiV1UsersByIdResponses,
    PutApiV1UsersByIdErrors,
    ThrowOnError
  >({
    url: '/api/v1/users/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * List Roles
 *
 * This endpoint retrieves a list of role assigned to a user
 */
export const getApiV1UsersByUserIdListRoles = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetApiV1UsersByUserIdListRolesData, ThrowOnError>
) => {
  return (options.client ?? client).get<
    GetApiV1UsersByUserIdListRolesResponses,
    GetApiV1UsersByUserIdListRolesErrors,
    ThrowOnError
  >({
    url: '/api/v1/users/{userId}/list-roles',
    ...options,
  });
};
