// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:6173' | 'http://localhost:6173' | (string & {});
};

export type ErrorResponse = {
  error: string;
  message: string;
};

export type Pagination = {
  count: number;
  currentPage: number;
  nextPage: number;
  pageSize: number;
  pages: number;
  previousPage: number;
};

export type Role = {
  createdAt: string;
  description: string;
  id: string;
  name: string;
  permissions: Array<string>;
  updatedAt: string;
};

export type Roles = Array<Role>;

export type SuccessResponse = {
  item?: User | Role;
  items?: Users | Roles;
  pagination?: Pagination;
};

export type User = {
  bio?: string;
  createdAt: string;
  id: string;
  image?: string;
  mfaEnabled: boolean;
  mfaVerified: boolean;
  name: string;
  updatedAt: string;
  username: string;
};

export type Users = Array<User>;

/**
 * The authorization code received from the OAuth provider.
 */
export type Code = string;

/**
 * Disable pagination.
 */
export type DisablePagination = boolean;

/**
 * The entity id.
 */
export type Id = string;

/**
 * The page number.
 */
export type Page = number;

/**
 * The number of items to return per page.
 */
export type PageSize = number;

/**
 * The related entities to preload.
 */
export type Preload = Array<string>;

/**
 * The columns to search in.
 */
export type SearchColumn = Array<string>;

/**
 * The search term to filter results.
 */
export type SearchTerm = string;

/**
 * The state parameter to maintain state between the request and callback.
 */
export type State = string;

/**
 * The url to redirect to after authentication.
 */
export type To = string;

/**
 * The payload to create a new role.
 */
export type CreateRolePayload = {
  description: string;
  name: string;
};

/**
 * The payload to create a new user.
 */
export type CreateUserPayload = {
  bio?: string | null;
  image?: string;
  name: string;
  username: string;
};

/**
 * The payload to update an existing role.
 */
export type UpdateRolePayload = {
  description?: string;
  name?: string;
  permissions?: Array<string>;
};

/**
 * The payload to update an existing user.
 */
export type UpdateUserPayload = {
  bio?: string | null;
  image?: string;
  mfaEnabled?: boolean;
  mfaVerified?: boolean;
  name?: string;
  username?: string;
};

export type GetApiV1AuthenticationCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/authentication/check';
};

export type GetApiV1AuthenticationCheckErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type GetApiV1AuthenticationCheckError =
  GetApiV1AuthenticationCheckErrors[keyof GetApiV1AuthenticationCheckErrors];

export type GetApiV1AuthenticationCheckResponses = {
  /**
   * The user is authenticated.
   */
  200: SuccessResponse;
};

export type GetApiV1AuthenticationCheckResponse =
  GetApiV1AuthenticationCheckResponses[keyof GetApiV1AuthenticationCheckResponses];

export type PostApiV1AuthenticationLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/authentication/logout';
};

export type PostApiV1AuthenticationLogoutErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type PostApiV1AuthenticationLogoutError =
  PostApiV1AuthenticationLogoutErrors[keyof PostApiV1AuthenticationLogoutErrors];

export type PostApiV1AuthenticationLogoutResponses = {
  /**
   * The user is logged out.
   */
  200: SuccessResponse;
};

export type PostApiV1AuthenticationLogoutResponse =
  PostApiV1AuthenticationLogoutResponses[keyof PostApiV1AuthenticationLogoutResponses];

export type GetApiV1AuthenticationMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/authentication/me';
};

export type GetApiV1AuthenticationMeErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type GetApiV1AuthenticationMeError =
  GetApiV1AuthenticationMeErrors[keyof GetApiV1AuthenticationMeErrors];

export type GetApiV1AuthenticationMeResponses = {
  /**
   * Returns the current user's information.
   */
  200: SuccessResponse;
};

export type GetApiV1AuthenticationMeResponse =
  GetApiV1AuthenticationMeResponses[keyof GetApiV1AuthenticationMeResponses];

export type GetApiV1AuthenticationMfaTotpEnableData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/authentication/mfa/totp/enable';
};

export type GetApiV1AuthenticationMfaTotpEnableErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type GetApiV1AuthenticationMfaTotpEnableError =
  GetApiV1AuthenticationMfaTotpEnableErrors[keyof GetApiV1AuthenticationMfaTotpEnableErrors];

export type GetApiV1AuthenticationMfaTotpEnableResponses = {
  /**
   * The MFA QR code has been generated and returned.
   */
  200: SuccessResponse;
};

export type GetApiV1AuthenticationMfaTotpEnableResponse =
  GetApiV1AuthenticationMfaTotpEnableResponses[keyof GetApiV1AuthenticationMfaTotpEnableResponses];

export type PostApiV1AuthenticationMfaTotpResetByIdData = {
  body?: never;
  path: {
    /**
     * The entity id.
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/authentication/mfa/totp/reset/{id}';
};

export type PostApiV1AuthenticationMfaTotpResetByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type PostApiV1AuthenticationMfaTotpResetByIdError =
  PostApiV1AuthenticationMfaTotpResetByIdErrors[keyof PostApiV1AuthenticationMfaTotpResetByIdErrors];

export type PostApiV1AuthenticationMfaTotpResetByIdResponses = {
  /**
   * The MFA code has been reset successfully.
   */
  200: SuccessResponse;
};

export type PostApiV1AuthenticationMfaTotpResetByIdResponse =
  PostApiV1AuthenticationMfaTotpResetByIdResponses[keyof PostApiV1AuthenticationMfaTotpResetByIdResponses];

export type PostApiV1AuthenticationMfaTotpVerifyData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * The authorization code received from the OAuth provider.
     */
    code?: string;
  };
  url: '/api/v1/authentication/mfa/totp/verify';
};

export type PostApiV1AuthenticationMfaTotpVerifyErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type PostApiV1AuthenticationMfaTotpVerifyError =
  PostApiV1AuthenticationMfaTotpVerifyErrors[keyof PostApiV1AuthenticationMfaTotpVerifyErrors];

export type PostApiV1AuthenticationMfaTotpVerifyResponses = {
  /**
   * The MFA code has been verified successfully.
   */
  200: SuccessResponse;
};

export type PostApiV1AuthenticationMfaTotpVerifyResponse =
  PostApiV1AuthenticationMfaTotpVerifyResponses[keyof PostApiV1AuthenticationMfaTotpVerifyResponses];

export type GetApiV1RolesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Disable pagination.
     */
    disablePagination?: boolean;
    /**
     * The page number.
     */
    page?: number;
    /**
     * The number of items to return per page.
     */
    pageSize?: number;
    /**
     * The related entities to preload.
     */
    preload?: Array<string>;
    /**
     * The search term to filter results.
     */
    searchTerm?: string;
    /**
     * The columns to search in.
     */
    searchColumn?: Array<string>;
  };
  url: '/api/v1/roles';
};

export type GetApiV1RolesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type GetApiV1RolesError = GetApiV1RolesErrors[keyof GetApiV1RolesErrors];

export type GetApiV1RolesResponses = {
  /**
   * Roles retrieved successfully.
   */
  200: SuccessResponse;
};

export type GetApiV1RolesResponse =
  GetApiV1RolesResponses[keyof GetApiV1RolesResponses];

export type PostApiV1RolesData = {
  /**
   * The payload to create a new role.
   */
  body: CreateRolePayload;
  path?: never;
  query?: never;
  url: '/api/v1/roles';
};

export type PostApiV1RolesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type PostApiV1RolesError =
  PostApiV1RolesErrors[keyof PostApiV1RolesErrors];

export type PostApiV1RolesResponses = {
  /**
   * Role created successfully.
   */
  200: SuccessResponse;
};

export type PostApiV1RolesResponse =
  PostApiV1RolesResponses[keyof PostApiV1RolesResponses];

export type DeleteApiV1RolesByIdData = {
  body?: never;
  path: {
    /**
     * The entity id.
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/roles/{id}';
};

export type DeleteApiV1RolesByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type DeleteApiV1RolesByIdError =
  DeleteApiV1RolesByIdErrors[keyof DeleteApiV1RolesByIdErrors];

export type DeleteApiV1RolesByIdResponses = {
  /**
   * Role deleted successfully.
   */
  200: SuccessResponse;
};

export type DeleteApiV1RolesByIdResponse =
  DeleteApiV1RolesByIdResponses[keyof DeleteApiV1RolesByIdResponses];

export type GetApiV1RolesByIdData = {
  body?: never;
  path: {
    /**
     * The entity id.
     */
    id: string;
  };
  query?: {
    /**
     * The related entities to preload.
     */
    preload?: Array<string>;
  };
  url: '/api/v1/roles/{id}';
};

export type GetApiV1RolesByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type GetApiV1RolesByIdError =
  GetApiV1RolesByIdErrors[keyof GetApiV1RolesByIdErrors];

export type GetApiV1RolesByIdResponses = {
  /**
   * Role retrieved successfully.
   */
  200: SuccessResponse;
};

export type GetApiV1RolesByIdResponse =
  GetApiV1RolesByIdResponses[keyof GetApiV1RolesByIdResponses];

export type PutApiV1RolesByIdData = {
  /**
   * The payload to update an existing role.
   */
  body: UpdateRolePayload;
  path: {
    /**
     * The entity id.
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/roles/{id}';
};

export type PutApiV1RolesByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type PutApiV1RolesByIdError =
  PutApiV1RolesByIdErrors[keyof PutApiV1RolesByIdErrors];

export type PutApiV1RolesByIdResponses = {
  /**
   * Role updated successfully.
   */
  200: SuccessResponse;
};

export type PutApiV1RolesByIdResponse =
  PutApiV1RolesByIdResponses[keyof PutApiV1RolesByIdResponses];

export type GetApiV1UsersData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Disable pagination.
     */
    disablePagination?: boolean;
    /**
     * The page number.
     */
    page?: number;
    /**
     * The number of items to return per page.
     */
    pageSize?: number;
    /**
     * The related entities to preload.
     */
    preload?: Array<string>;
    /**
     * The search term to filter results.
     */
    searchTerm?: string;
    /**
     * The columns to search in.
     */
    searchColumn?: Array<string>;
  };
  url: '/api/v1/users';
};

export type GetApiV1UsersErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type GetApiV1UsersError = GetApiV1UsersErrors[keyof GetApiV1UsersErrors];

export type GetApiV1UsersResponses = {
  /**
   * Users retrieved successfully.
   */
  200: SuccessResponse;
};

export type GetApiV1UsersResponse =
  GetApiV1UsersResponses[keyof GetApiV1UsersResponses];

export type PostApiV1UsersData = {
  /**
   * The payload to create a new user.
   */
  body: CreateUserPayload;
  path?: never;
  query?: never;
  url: '/api/v1/users';
};

export type PostApiV1UsersErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type PostApiV1UsersError =
  PostApiV1UsersErrors[keyof PostApiV1UsersErrors];

export type PostApiV1UsersResponses = {
  /**
   * User created successfully.
   */
  200: SuccessResponse;
};

export type PostApiV1UsersResponse =
  PostApiV1UsersResponses[keyof PostApiV1UsersResponses];

export type PostApiV1UsersAssignRoleByUserIdByRoleIdData = {
  body?: never;
  path: {
    userId: string;
    roleId: string;
  };
  query?: never;
  url: '/api/v1/users/assign-role/{userId}/{roleId}';
};

export type PostApiV1UsersAssignRoleByUserIdByRoleIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type PostApiV1UsersAssignRoleByUserIdByRoleIdError =
  PostApiV1UsersAssignRoleByUserIdByRoleIdErrors[keyof PostApiV1UsersAssignRoleByUserIdByRoleIdErrors];

export type PostApiV1UsersAssignRoleByUserIdByRoleIdResponses = {
  /**
   * Role assigned to User successfully.
   */
  200: SuccessResponse;
};

export type PostApiV1UsersAssignRoleByUserIdByRoleIdResponse =
  PostApiV1UsersAssignRoleByUserIdByRoleIdResponses[keyof PostApiV1UsersAssignRoleByUserIdByRoleIdResponses];

export type PostApiV1UsersUnassignRoleByUserIdByRoleIdData = {
  body?: never;
  path: {
    userId: string;
    roleId: string;
  };
  query?: never;
  url: '/api/v1/users/unassign-role/{userId}/{roleId}';
};

export type PostApiV1UsersUnassignRoleByUserIdByRoleIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type PostApiV1UsersUnassignRoleByUserIdByRoleIdError =
  PostApiV1UsersUnassignRoleByUserIdByRoleIdErrors[keyof PostApiV1UsersUnassignRoleByUserIdByRoleIdErrors];

export type PostApiV1UsersUnassignRoleByUserIdByRoleIdResponses = {
  /**
   * Role assigned to User successfully.
   */
  200: SuccessResponse;
};

export type PostApiV1UsersUnassignRoleByUserIdByRoleIdResponse =
  PostApiV1UsersUnassignRoleByUserIdByRoleIdResponses[keyof PostApiV1UsersUnassignRoleByUserIdByRoleIdResponses];

export type DeleteApiV1UsersByIdData = {
  body?: never;
  path: {
    /**
     * The entity id.
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/users/{id}';
};

export type DeleteApiV1UsersByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type DeleteApiV1UsersByIdError =
  DeleteApiV1UsersByIdErrors[keyof DeleteApiV1UsersByIdErrors];

export type DeleteApiV1UsersByIdResponses = {
  /**
   * User deleted successfully.
   */
  200: SuccessResponse;
};

export type DeleteApiV1UsersByIdResponse =
  DeleteApiV1UsersByIdResponses[keyof DeleteApiV1UsersByIdResponses];

export type GetApiV1UsersByIdData = {
  body?: never;
  path: {
    /**
     * The entity id.
     */
    id: string;
  };
  query?: {
    /**
     * The related entities to preload.
     */
    preload?: Array<string>;
  };
  url: '/api/v1/users/{id}';
};

export type GetApiV1UsersByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type GetApiV1UsersByIdError =
  GetApiV1UsersByIdErrors[keyof GetApiV1UsersByIdErrors];

export type GetApiV1UsersByIdResponses = {
  /**
   * User retrieved successfully.
   */
  200: SuccessResponse;
};

export type GetApiV1UsersByIdResponse =
  GetApiV1UsersByIdResponses[keyof GetApiV1UsersByIdResponses];

export type PutApiV1UsersByIdData = {
  /**
   * The payload to update an existing user.
   */
  body: UpdateUserPayload;
  path: {
    /**
     * The entity id.
     */
    id: string;
  };
  query?: never;
  url: '/api/v1/users/{id}';
};

export type PutApiV1UsersByIdErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type PutApiV1UsersByIdError =
  PutApiV1UsersByIdErrors[keyof PutApiV1UsersByIdErrors];

export type PutApiV1UsersByIdResponses = {
  /**
   * User updated successfully.
   */
  200: SuccessResponse;
};

export type PutApiV1UsersByIdResponse =
  PutApiV1UsersByIdResponses[keyof PutApiV1UsersByIdResponses];

export type GetApiV1UsersByUserIdListRolesData = {
  body?: never;
  path: {
    userId: string;
  };
  query?: {
    /**
     * Disable pagination.
     */
    disablePagination?: boolean;
    /**
     * The page number.
     */
    page?: number;
    /**
     * The number of items to return per page.
     */
    pageSize?: number;
    /**
     * The related entities to preload.
     */
    preload?: Array<string>;
    /**
     * The search term to filter results.
     */
    searchTerm?: string;
    /**
     * The columns to search in.
     */
    searchColumn?: Array<string>;
  };
  url: '/api/v1/users/{userId}/list-roles';
};

export type GetApiV1UsersByUserIdListRolesErrors = {
  /**
   * Bad Request
   */
  400: ErrorResponse;
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Forbidden
   */
  403: ErrorResponse;
  /**
   * Not Found
   */
  404: ErrorResponse;
  /**
   * Internal Server Error
   */
  500: ErrorResponse;
  default: unknown;
};

export type GetApiV1UsersByUserIdListRolesError =
  GetApiV1UsersByUserIdListRolesErrors[keyof GetApiV1UsersByUserIdListRolesErrors];

export type GetApiV1UsersByUserIdListRolesResponses = {
  /**
   * User Roles retrieved successfully.
   */
  200: SuccessResponse;
};

export type GetApiV1UsersByUserIdListRolesResponse =
  GetApiV1UsersByUserIdListRolesResponses[keyof GetApiV1UsersByUserIdListRolesResponses];
