// This file is auto-generated by @hey-api/openapi-ts
import { z } from 'zod';

export const zErrorResponse = z.object({
  error: z.string(),
  message: z.string(),
});

export const zPagination = z.object({
  count: z.int().default(0),
  currentPage: z.int().default(1),
  nextPage: z.int().default(1),
  pageSize: z.int().default(10),
  pages: z.int().default(1),
  previousPage: z.int().default(1),
});

export const zRole = z.object({
  createdAt: z.iso.datetime(),
  description: z.string(),
  id: z.uuid(),
  name: z.string(),
  permissions: z.array(z.string()),
  updatedAt: z.iso.datetime(),
});

export const zRoles = z.array(zRole);

export const zUser = z.object({
  bio: z.optional(z.string()),
  createdAt: z.iso.datetime(),
  id: z.uuid(),
  image: z.optional(z.url()),
  mfaEnabled: z.boolean(),
  mfaVerified: z.boolean(),
  name: z.string(),
  updatedAt: z.iso.datetime(),
  username: z
    .string()
    .regex(
      /(?:\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b)|(?:\b(?:\+?\d{1,3}[-.\s]?)?(?:\(?\d{2,4}\)?[-.\s]?)?\d{3,4}[-.\s]?\d{3,4}\b)/
    ),
});

export const zUsers = z.array(zUser);

export const zSuccessResponse = z.object({
  item: z.optional(z.union([zUser, zRole])),
  items: z.optional(z.union([zUsers, zRoles])),
  pagination: z.optional(zPagination),
});

/**
 * The authorization code received from the OAuth provider.
 */
export const zCode = z.string();

/**
 * Disable pagination.
 */
export const zDisablePagination = z.boolean().default(false);

/**
 * The entity id.
 */
export const zId = z.uuid();

/**
 * The page number.
 */
export const zPage = z.coerce.bigint().default(BigInt(1));

/**
 * The number of items to return per page.
 */
export const zPageSize = z.coerce.bigint().default(BigInt(10));

/**
 * The related entities to preload.
 */
export const zPreload = z.array(z.string());

/**
 * The columns to search in.
 */
export const zSearchColumn = z.array(z.string());

/**
 * The search term to filter results.
 */
export const zSearchTerm = z.string();

/**
 * The state parameter to maintain state between the request and callback.
 */
export const zState = z.string().default('http://localhost:3000');

/**
 * The url to redirect to after authentication.
 */
export const zTo = z.string().default('http://localhost:3000');

/**
 * The payload to create a new role.
 */
export const zCreateRolePayload = z.object({
  description: z.string(),
  name: z.string(),
});

/**
 * The payload to create a new user.
 */
export const zCreateUserPayload = z.object({
  bio: z.optional(z.union([z.string(), z.null()])),
  image: z.optional(z.url()),
  name: z.string(),
  username: z
    .string()
    .regex(
      /(?:\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b)|(?:\b(?:\+?\d{1,3}[-.\s]?)?(?:\(?\d{2,4}\)?[-.\s]?)?\d{3,4}[-.\s]?\d{3,4}\b)/
    ),
});

/**
 * The payload to update an existing role.
 */
export const zUpdateRolePayload = z.object({
  description: z.optional(z.string()),
  name: z.optional(z.string()),
  permissions: z.optional(z.array(z.string())),
});

/**
 * The payload to update an existing user.
 */
export const zUpdateUserPayload = z.object({
  bio: z.optional(z.union([z.string(), z.null()])),
  image: z.optional(z.url()),
  mfaEnabled: z.optional(z.boolean()),
  mfaVerified: z.optional(z.boolean()),
  name: z.optional(z.string()),
  username: z.optional(
    z
      .string()
      .regex(
        /(?:\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b)|(?:\b(?:\+?\d{1,3}[-.\s]?)?(?:\(?\d{2,4}\)?[-.\s]?)?\d{3,4}[-.\s]?\d{3,4}\b)/
      )
  ),
});

export const zGetApiV1AuthenticationCheckData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The user is authenticated.
 */
export const zGetApiV1AuthenticationCheckResponse = zSuccessResponse;

export const zPostApiV1AuthenticationLogoutData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The user is logged out.
 */
export const zPostApiV1AuthenticationLogoutResponse = zSuccessResponse;

export const zGetApiV1AuthenticationMeData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Returns the current user's information.
 */
export const zGetApiV1AuthenticationMeResponse = zSuccessResponse;

export const zGetApiV1AuthenticationMfaTotpEnableData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * The MFA QR code has been generated and returned.
 */
export const zGetApiV1AuthenticationMfaTotpEnableResponse = zSuccessResponse;

export const zPostApiV1AuthenticationMfaTotpResetByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * The MFA code has been reset successfully.
 */
export const zPostApiV1AuthenticationMfaTotpResetByIdResponse =
  zSuccessResponse;

export const zPostApiV1AuthenticationMfaTotpVerifyData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      code: z.optional(z.string()),
    })
  ),
});

/**
 * The MFA code has been verified successfully.
 */
export const zPostApiV1AuthenticationMfaTotpVerifyResponse = zSuccessResponse;

export const zGetApiV1RolesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      disablePagination: z.optional(z.boolean()).default(false),
      page: z.optional(z.coerce.bigint()).default(BigInt(1)),
      pageSize: z.optional(z.coerce.bigint()).default(BigInt(10)),
      preload: z.optional(z.array(z.string())),
      searchTerm: z.optional(z.string()),
      searchColumn: z.optional(z.array(z.string())),
    })
  ),
});

/**
 * Roles retrieved successfully.
 */
export const zGetApiV1RolesResponse = zSuccessResponse;

export const zPostApiV1RolesData = z.object({
  body: zCreateRolePayload,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Role created successfully.
 */
export const zPostApiV1RolesResponse = zSuccessResponse;

export const zDeleteApiV1RolesByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Role deleted successfully.
 */
export const zDeleteApiV1RolesByIdResponse = zSuccessResponse;

export const zGetApiV1RolesByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(
    z.object({
      preload: z.optional(z.array(z.string())),
    })
  ),
});

/**
 * Role retrieved successfully.
 */
export const zGetApiV1RolesByIdResponse = zSuccessResponse;

export const zPutApiV1RolesByIdData = z.object({
  body: zUpdateRolePayload,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Role updated successfully.
 */
export const zPutApiV1RolesByIdResponse = zSuccessResponse;

export const zGetApiV1UsersData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      disablePagination: z.optional(z.boolean()).default(false),
      page: z.optional(z.coerce.bigint()).default(BigInt(1)),
      pageSize: z.optional(z.coerce.bigint()).default(BigInt(10)),
      preload: z.optional(z.array(z.string())),
      searchTerm: z.optional(z.string()),
      searchColumn: z.optional(z.array(z.string())),
    })
  ),
});

/**
 * Users retrieved successfully.
 */
export const zGetApiV1UsersResponse = zSuccessResponse;

export const zPostApiV1UsersData = z.object({
  body: zCreateUserPayload,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * User created successfully.
 */
export const zPostApiV1UsersResponse = zSuccessResponse;

export const zPostApiV1UsersAssignRoleByUserIdByRoleIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.uuid(),
    roleId: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Role assigned to User successfully.
 */
export const zPostApiV1UsersAssignRoleByUserIdByRoleIdResponse =
  zSuccessResponse;

export const zPostApiV1UsersUnassignRoleByUserIdByRoleIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.uuid(),
    roleId: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Role assigned to User successfully.
 */
export const zPostApiV1UsersUnassignRoleByUserIdByRoleIdResponse =
  zSuccessResponse;

export const zDeleteApiV1UsersByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * User deleted successfully.
 */
export const zDeleteApiV1UsersByIdResponse = zSuccessResponse;

export const zGetApiV1UsersByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(
    z.object({
      preload: z.optional(z.array(z.string())),
    })
  ),
});

/**
 * User retrieved successfully.
 */
export const zGetApiV1UsersByIdResponse = zSuccessResponse;

export const zPutApiV1UsersByIdData = z.object({
  body: zUpdateUserPayload,
  path: z.object({
    id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * User updated successfully.
 */
export const zPutApiV1UsersByIdResponse = zSuccessResponse;

export const zGetApiV1UsersByUserIdListRolesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    userId: z.uuid(),
  }),
  query: z.optional(
    z.object({
      disablePagination: z.optional(z.boolean()).default(false),
      page: z.optional(z.coerce.bigint()).default(BigInt(1)),
      pageSize: z.optional(z.coerce.bigint()).default(BigInt(10)),
      preload: z.optional(z.array(z.string())),
      searchTerm: z.optional(z.string()),
      searchColumn: z.optional(z.array(z.string())),
    })
  ),
});

/**
 * User Roles retrieved successfully.
 */
export const zGetApiV1UsersByUserIdListRolesResponse = zSuccessResponse;
