/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoauthRouteImport } from './routes/_noauth'
import { Route as MfaRouteImport } from './routes/_mfa'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as NoauthSignInRouteImport } from './routes/_noauth/sign-in'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthRolesIndexRouteImport } from './routes/_auth/roles/index'
import { Route as MfaMfaVerifyRouteImport } from './routes/_mfa/mfa/verify'
import { Route as MfaMfaEnableRouteImport } from './routes/_mfa/mfa/enable'
import { Route as AuthUsersIdRouteImport } from './routes/_auth/users/$id'
import { Route as AuthRolesCreateRouteImport } from './routes/_auth/roles/create'
import { Route as AuthRolesIdRouteImport } from './routes/_auth/roles/$id'
import { Route as AuthUsersIdIndexRouteImport } from './routes/_auth/users/$id/index'
import { Route as AuthRolesIdIndexRouteImport } from './routes/_auth/roles/$id/index'
import { Route as AuthUsersIdSecurityRouteImport } from './routes/_auth/users/$id/security'
import { Route as AuthUsersIdRolesRouteImport } from './routes/_auth/users/$id/roles'
import { Route as AuthRolesIdPermissionsRouteImport } from './routes/_auth/roles/$id/permissions'

const NoauthRoute = NoauthRouteImport.update({
  id: '/_noauth',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/_mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const NoauthSignInRoute = NoauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => NoauthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesIndexRoute = AuthRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthRoute,
} as any)
const MfaMfaVerifyRoute = MfaMfaVerifyRouteImport.update({
  id: '/mfa/verify',
  path: '/mfa/verify',
  getParentRoute: () => MfaRoute,
} as any)
const MfaMfaEnableRoute = MfaMfaEnableRouteImport.update({
  id: '/mfa/enable',
  path: '/mfa/enable',
  getParentRoute: () => MfaRoute,
} as any)
const AuthUsersIdRoute = AuthUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesCreateRoute = AuthRolesCreateRouteImport.update({
  id: '/roles/create',
  path: '/roles/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRolesIdRoute = AuthRolesIdRouteImport.update({
  id: '/roles/$id',
  path: '/roles/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIdIndexRoute = AuthUsersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthUsersIdRoute,
} as any)
const AuthRolesIdIndexRoute = AuthRolesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRolesIdRoute,
} as any)
const AuthUsersIdSecurityRoute = AuthUsersIdSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthUsersIdRoute,
} as any)
const AuthUsersIdRolesRoute = AuthUsersIdRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthUsersIdRoute,
} as any)
const AuthRolesIdPermissionsRoute = AuthRolesIdPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AuthRolesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof NoauthSignInRoute
  '/': typeof AuthIndexRoute
  '/roles/$id': typeof AuthRolesIdRouteWithChildren
  '/roles/create': typeof AuthRolesCreateRoute
  '/users/$id': typeof AuthUsersIdRouteWithChildren
  '/mfa/enable': typeof MfaMfaEnableRoute
  '/mfa/verify': typeof MfaMfaVerifyRoute
  '/roles': typeof AuthRolesIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/roles/$id/permissions': typeof AuthRolesIdPermissionsRoute
  '/users/$id/roles': typeof AuthUsersIdRolesRoute
  '/users/$id/security': typeof AuthUsersIdSecurityRoute
  '/roles/$id/': typeof AuthRolesIdIndexRoute
  '/users/$id/': typeof AuthUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof NoauthSignInRoute
  '/': typeof AuthIndexRoute
  '/roles/create': typeof AuthRolesCreateRoute
  '/mfa/enable': typeof MfaMfaEnableRoute
  '/mfa/verify': typeof MfaMfaVerifyRoute
  '/roles': typeof AuthRolesIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/roles/$id/permissions': typeof AuthRolesIdPermissionsRoute
  '/users/$id/roles': typeof AuthUsersIdRolesRoute
  '/users/$id/security': typeof AuthUsersIdSecurityRoute
  '/roles/$id': typeof AuthRolesIdIndexRoute
  '/users/$id': typeof AuthUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_mfa': typeof MfaRouteWithChildren
  '/_noauth': typeof NoauthRouteWithChildren
  '/_noauth/sign-in': typeof NoauthSignInRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/roles/$id': typeof AuthRolesIdRouteWithChildren
  '/_auth/roles/create': typeof AuthRolesCreateRoute
  '/_auth/users/$id': typeof AuthUsersIdRouteWithChildren
  '/_mfa/mfa/enable': typeof MfaMfaEnableRoute
  '/_mfa/mfa/verify': typeof MfaMfaVerifyRoute
  '/_auth/roles/': typeof AuthRolesIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/roles/$id/permissions': typeof AuthRolesIdPermissionsRoute
  '/_auth/users/$id/roles': typeof AuthUsersIdRolesRoute
  '/_auth/users/$id/security': typeof AuthUsersIdSecurityRoute
  '/_auth/roles/$id/': typeof AuthRolesIdIndexRoute
  '/_auth/users/$id/': typeof AuthUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sign-in'
    | '/'
    | '/roles/$id'
    | '/roles/create'
    | '/users/$id'
    | '/mfa/enable'
    | '/mfa/verify'
    | '/roles'
    | '/users'
    | '/roles/$id/permissions'
    | '/users/$id/roles'
    | '/users/$id/security'
    | '/roles/$id/'
    | '/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/'
    | '/roles/create'
    | '/mfa/enable'
    | '/mfa/verify'
    | '/roles'
    | '/users'
    | '/roles/$id/permissions'
    | '/users/$id/roles'
    | '/users/$id/security'
    | '/roles/$id'
    | '/users/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_mfa'
    | '/_noauth'
    | '/_noauth/sign-in'
    | '/_auth/'
    | '/_auth/roles/$id'
    | '/_auth/roles/create'
    | '/_auth/users/$id'
    | '/_mfa/mfa/enable'
    | '/_mfa/mfa/verify'
    | '/_auth/roles/'
    | '/_auth/users/'
    | '/_auth/roles/$id/permissions'
    | '/_auth/users/$id/roles'
    | '/_auth/users/$id/security'
    | '/_auth/roles/$id/'
    | '/_auth/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MfaRoute: typeof MfaRouteWithChildren
  NoauthRoute: typeof NoauthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_noauth': {
      id: '/_noauth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NoauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mfa': {
      id: '/_mfa'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_noauth/sign-in': {
      id: '/_noauth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof NoauthSignInRouteImport
      parentRoute: typeof NoauthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles/': {
      id: '/_auth/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthRolesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_mfa/mfa/verify': {
      id: '/_mfa/mfa/verify'
      path: '/mfa/verify'
      fullPath: '/mfa/verify'
      preLoaderRoute: typeof MfaMfaVerifyRouteImport
      parentRoute: typeof MfaRoute
    }
    '/_mfa/mfa/enable': {
      id: '/_mfa/mfa/enable'
      path: '/mfa/enable'
      fullPath: '/mfa/enable'
      preLoaderRoute: typeof MfaMfaEnableRouteImport
      parentRoute: typeof MfaRoute
    }
    '/_auth/users/$id': {
      id: '/_auth/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthUsersIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles/create': {
      id: '/_auth/roles/create'
      path: '/roles/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof AuthRolesCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/roles/$id': {
      id: '/_auth/roles/$id'
      path: '/roles/$id'
      fullPath: '/roles/$id'
      preLoaderRoute: typeof AuthRolesIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/$id/': {
      id: '/_auth/users/$id/'
      path: '/'
      fullPath: '/users/$id/'
      preLoaderRoute: typeof AuthUsersIdIndexRouteImport
      parentRoute: typeof AuthUsersIdRoute
    }
    '/_auth/roles/$id/': {
      id: '/_auth/roles/$id/'
      path: '/'
      fullPath: '/roles/$id/'
      preLoaderRoute: typeof AuthRolesIdIndexRouteImport
      parentRoute: typeof AuthRolesIdRoute
    }
    '/_auth/users/$id/security': {
      id: '/_auth/users/$id/security'
      path: '/security'
      fullPath: '/users/$id/security'
      preLoaderRoute: typeof AuthUsersIdSecurityRouteImport
      parentRoute: typeof AuthUsersIdRoute
    }
    '/_auth/users/$id/roles': {
      id: '/_auth/users/$id/roles'
      path: '/roles'
      fullPath: '/users/$id/roles'
      preLoaderRoute: typeof AuthUsersIdRolesRouteImport
      parentRoute: typeof AuthUsersIdRoute
    }
    '/_auth/roles/$id/permissions': {
      id: '/_auth/roles/$id/permissions'
      path: '/permissions'
      fullPath: '/roles/$id/permissions'
      preLoaderRoute: typeof AuthRolesIdPermissionsRouteImport
      parentRoute: typeof AuthRolesIdRoute
    }
  }
}

interface AuthRolesIdRouteChildren {
  AuthRolesIdPermissionsRoute: typeof AuthRolesIdPermissionsRoute
  AuthRolesIdIndexRoute: typeof AuthRolesIdIndexRoute
}

const AuthRolesIdRouteChildren: AuthRolesIdRouteChildren = {
  AuthRolesIdPermissionsRoute: AuthRolesIdPermissionsRoute,
  AuthRolesIdIndexRoute: AuthRolesIdIndexRoute,
}

const AuthRolesIdRouteWithChildren = AuthRolesIdRoute._addFileChildren(
  AuthRolesIdRouteChildren,
)

interface AuthUsersIdRouteChildren {
  AuthUsersIdRolesRoute: typeof AuthUsersIdRolesRoute
  AuthUsersIdSecurityRoute: typeof AuthUsersIdSecurityRoute
  AuthUsersIdIndexRoute: typeof AuthUsersIdIndexRoute
}

const AuthUsersIdRouteChildren: AuthUsersIdRouteChildren = {
  AuthUsersIdRolesRoute: AuthUsersIdRolesRoute,
  AuthUsersIdSecurityRoute: AuthUsersIdSecurityRoute,
  AuthUsersIdIndexRoute: AuthUsersIdIndexRoute,
}

const AuthUsersIdRouteWithChildren = AuthUsersIdRoute._addFileChildren(
  AuthUsersIdRouteChildren,
)

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthRolesIdRoute: typeof AuthRolesIdRouteWithChildren
  AuthRolesCreateRoute: typeof AuthRolesCreateRoute
  AuthUsersIdRoute: typeof AuthUsersIdRouteWithChildren
  AuthRolesIndexRoute: typeof AuthRolesIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthRolesIdRoute: AuthRolesIdRouteWithChildren,
  AuthRolesCreateRoute: AuthRolesCreateRoute,
  AuthUsersIdRoute: AuthUsersIdRouteWithChildren,
  AuthRolesIndexRoute: AuthRolesIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MfaRouteChildren {
  MfaMfaEnableRoute: typeof MfaMfaEnableRoute
  MfaMfaVerifyRoute: typeof MfaMfaVerifyRoute
}

const MfaRouteChildren: MfaRouteChildren = {
  MfaMfaEnableRoute: MfaMfaEnableRoute,
  MfaMfaVerifyRoute: MfaMfaVerifyRoute,
}

const MfaRouteWithChildren = MfaRoute._addFileChildren(MfaRouteChildren)

interface NoauthRouteChildren {
  NoauthSignInRoute: typeof NoauthSignInRoute
}

const NoauthRouteChildren: NoauthRouteChildren = {
  NoauthSignInRoute: NoauthSignInRoute,
}

const NoauthRouteWithChildren =
  NoauthRoute._addFileChildren(NoauthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MfaRoute: MfaRouteWithChildren,
  NoauthRoute: NoauthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
