// This file is auto-generated by @hey-api/openapi-ts
import {
  type InfiniteData,
  type UseMutationOptions,
  infiniteQueryOptions,
  queryOptions,
} from '@tanstack/react-query';

import { client } from '../client.gen';
import {
  type Options,
  deleteApiV1RolesById,
  deleteApiV1UsersById,
  getApiV1AuthenticationCheck,
  getApiV1AuthenticationMe,
  getApiV1AuthenticationMfaTotpEnable,
  getApiV1Roles,
  getApiV1RolesById,
  getApiV1Users,
  getApiV1UsersById,
  getApiV1UsersByUserIdListRoles,
  postApiV1AuthenticationLogout,
  postApiV1AuthenticationMfaTotpResetById,
  postApiV1AuthenticationMfaTotpVerify,
  postApiV1Roles,
  postApiV1Users,
  postApiV1UsersAssignRoleByUserIdByRoleId,
  postApiV1UsersUnassignRoleByUserIdByRoleId,
  putApiV1RolesById,
  putApiV1UsersById,
} from '../sdk.gen';
import type {
  DeleteApiV1RolesByIdData,
  DeleteApiV1RolesByIdError,
  DeleteApiV1RolesByIdResponse,
  DeleteApiV1UsersByIdData,
  DeleteApiV1UsersByIdError,
  DeleteApiV1UsersByIdResponse,
  GetApiV1AuthenticationCheckData,
  GetApiV1AuthenticationMeData,
  GetApiV1AuthenticationMfaTotpEnableData,
  GetApiV1RolesByIdData,
  GetApiV1RolesData,
  GetApiV1RolesError,
  GetApiV1RolesResponse,
  GetApiV1UsersByIdData,
  GetApiV1UsersByUserIdListRolesData,
  GetApiV1UsersByUserIdListRolesError,
  GetApiV1UsersByUserIdListRolesResponse,
  GetApiV1UsersData,
  GetApiV1UsersError,
  GetApiV1UsersResponse,
  PostApiV1AuthenticationLogoutData,
  PostApiV1AuthenticationLogoutError,
  PostApiV1AuthenticationLogoutResponse,
  PostApiV1AuthenticationMfaTotpResetByIdData,
  PostApiV1AuthenticationMfaTotpResetByIdError,
  PostApiV1AuthenticationMfaTotpResetByIdResponse,
  PostApiV1AuthenticationMfaTotpVerifyData,
  PostApiV1AuthenticationMfaTotpVerifyError,
  PostApiV1AuthenticationMfaTotpVerifyResponse,
  PostApiV1RolesData,
  PostApiV1RolesError,
  PostApiV1RolesResponse,
  PostApiV1UsersAssignRoleByUserIdByRoleIdData,
  PostApiV1UsersAssignRoleByUserIdByRoleIdError,
  PostApiV1UsersAssignRoleByUserIdByRoleIdResponse,
  PostApiV1UsersData,
  PostApiV1UsersError,
  PostApiV1UsersResponse,
  PostApiV1UsersUnassignRoleByUserIdByRoleIdData,
  PostApiV1UsersUnassignRoleByUserIdByRoleIdError,
  PostApiV1UsersUnassignRoleByUserIdByRoleIdResponse,
  PutApiV1RolesByIdData,
  PutApiV1RolesByIdError,
  PutApiV1RolesByIdResponse,
  PutApiV1UsersByIdData,
  PutApiV1UsersByIdError,
  PutApiV1UsersByIdResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getApiV1AuthenticationCheckQueryKey = (
  options?: Options<GetApiV1AuthenticationCheckData>
) => createQueryKey('getApiV1AuthenticationCheck', options);

/**
 * Check Authentication Status
 *
 * Checks if a user is authenticated.
 */
export const getApiV1AuthenticationCheckOptions = (
  options?: Options<GetApiV1AuthenticationCheckData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1AuthenticationCheck({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1AuthenticationCheckQueryKey(options),
  });
};

/**
 * Logout User
 *
 * Logs out the authenticated user.
 */
export const postApiV1AuthenticationLogoutMutation = (
  options?: Partial<Options<PostApiV1AuthenticationLogoutData>>
): UseMutationOptions<
  PostApiV1AuthenticationLogoutResponse,
  PostApiV1AuthenticationLogoutError,
  Options<PostApiV1AuthenticationLogoutData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1AuthenticationLogoutResponse,
    PostApiV1AuthenticationLogoutError,
    Options<PostApiV1AuthenticationLogoutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiV1AuthenticationLogout({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1AuthenticationMeQueryKey = (
  options?: Options<GetApiV1AuthenticationMeData>
) => createQueryKey('getApiV1AuthenticationMe', options);

/**
 * Get Current User
 *
 * Returns the current user's information.
 */
export const getApiV1AuthenticationMeOptions = (
  options?: Options<GetApiV1AuthenticationMeData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1AuthenticationMe({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1AuthenticationMeQueryKey(options),
  });
};

export const getApiV1AuthenticationMfaTotpEnableQueryKey = (
  options?: Options<GetApiV1AuthenticationMfaTotpEnableData>
) => createQueryKey('getApiV1AuthenticationMfaTotpEnable', options);

/**
 * Enable TOTP MFA
 *
 * Enables Time-based One-Time Password (TOTP) Multi-Factor Authentication for the user.
 */
export const getApiV1AuthenticationMfaTotpEnableOptions = (
  options?: Options<GetApiV1AuthenticationMfaTotpEnableData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1AuthenticationMfaTotpEnable({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1AuthenticationMfaTotpEnableQueryKey(options),
  });
};

/**
 * Reset TOTP MFA
 *
 * Resets the Time-based One-Time Password (TOTP) Multi-Factor Authentication for the user.
 */
export const postApiV1AuthenticationMfaTotpResetByIdMutation = (
  options?: Partial<Options<PostApiV1AuthenticationMfaTotpResetByIdData>>
): UseMutationOptions<
  PostApiV1AuthenticationMfaTotpResetByIdResponse,
  PostApiV1AuthenticationMfaTotpResetByIdError,
  Options<PostApiV1AuthenticationMfaTotpResetByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1AuthenticationMfaTotpResetByIdResponse,
    PostApiV1AuthenticationMfaTotpResetByIdError,
    Options<PostApiV1AuthenticationMfaTotpResetByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiV1AuthenticationMfaTotpResetById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Verify TOTP MFA
 *
 * Verifies the Time-based One-Time Password (TOTP) Multi-Factor Authentication code for the user.
 */
export const postApiV1AuthenticationMfaTotpVerifyMutation = (
  options?: Partial<Options<PostApiV1AuthenticationMfaTotpVerifyData>>
): UseMutationOptions<
  PostApiV1AuthenticationMfaTotpVerifyResponse,
  PostApiV1AuthenticationMfaTotpVerifyError,
  Options<PostApiV1AuthenticationMfaTotpVerifyData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1AuthenticationMfaTotpVerifyResponse,
    PostApiV1AuthenticationMfaTotpVerifyError,
    Options<PostApiV1AuthenticationMfaTotpVerifyData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiV1AuthenticationMfaTotpVerify({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1RolesQueryKey = (options?: Options<GetApiV1RolesData>) =>
  createQueryKey('getApiV1Roles', options);

/**
 * Get Roles
 *
 * This endpoint retrieves all roles.
 */
export const getApiV1RolesOptions = (options?: Options<GetApiV1RolesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1Roles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1RolesQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = {
    ...queryKey[0],
  };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const getApiV1RolesInfiniteQueryKey = (
  options?: Options<GetApiV1RolesData>
): QueryKey<Options<GetApiV1RolesData>> =>
  createQueryKey('getApiV1Roles', options, true);

/**
 * Get Roles
 *
 * This endpoint retrieves all roles.
 */
export const getApiV1RolesInfiniteOptions = (
  options?: Options<GetApiV1RolesData>
) => {
  return infiniteQueryOptions<
    GetApiV1RolesResponse,
    GetApiV1RolesError,
    InfiniteData<GetApiV1RolesResponse>,
    QueryKey<Options<GetApiV1RolesData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiV1RolesData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiV1RolesData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV1Roles({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiV1RolesInfiniteQueryKey(options),
    }
  );
};

/**
 * Create Role
 *
 * This endpoint creates a new role.
 */
export const postApiV1RolesMutation = (
  options?: Partial<Options<PostApiV1RolesData>>
): UseMutationOptions<
  PostApiV1RolesResponse,
  PostApiV1RolesError,
  Options<PostApiV1RolesData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1RolesResponse,
    PostApiV1RolesError,
    Options<PostApiV1RolesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiV1Roles({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Role
 *
 * This endpoint deletes an existing role by their id.
 */
export const deleteApiV1RolesByIdMutation = (
  options?: Partial<Options<DeleteApiV1RolesByIdData>>
): UseMutationOptions<
  DeleteApiV1RolesByIdResponse,
  DeleteApiV1RolesByIdError,
  Options<DeleteApiV1RolesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiV1RolesByIdResponse,
    DeleteApiV1RolesByIdError,
    Options<DeleteApiV1RolesByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiV1RolesById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1RolesByIdQueryKey = (
  options: Options<GetApiV1RolesByIdData>
) => createQueryKey('getApiV1RolesById', options);

/**
 * Get Role
 *
 * This endpoint retrieves an existing role by their id.
 */
export const getApiV1RolesByIdOptions = (
  options: Options<GetApiV1RolesByIdData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1RolesById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1RolesByIdQueryKey(options),
  });
};

/**
 * Update Role
 *
 * This endpoint updates an existing role by their id.
 */
export const putApiV1RolesByIdMutation = (
  options?: Partial<Options<PutApiV1RolesByIdData>>
): UseMutationOptions<
  PutApiV1RolesByIdResponse,
  PutApiV1RolesByIdError,
  Options<PutApiV1RolesByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiV1RolesByIdResponse,
    PutApiV1RolesByIdError,
    Options<PutApiV1RolesByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiV1RolesById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1UsersQueryKey = (options?: Options<GetApiV1UsersData>) =>
  createQueryKey('getApiV1Users', options);

/**
 * Get Users
 *
 * This endpoint retrieves all users.
 */
export const getApiV1UsersOptions = (options?: Options<GetApiV1UsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1Users({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1UsersQueryKey(options),
  });
};

export const getApiV1UsersInfiniteQueryKey = (
  options?: Options<GetApiV1UsersData>
): QueryKey<Options<GetApiV1UsersData>> =>
  createQueryKey('getApiV1Users', options, true);

/**
 * Get Users
 *
 * This endpoint retrieves all users.
 */
export const getApiV1UsersInfiniteOptions = (
  options?: Options<GetApiV1UsersData>
) => {
  return infiniteQueryOptions<
    GetApiV1UsersResponse,
    GetApiV1UsersError,
    InfiniteData<GetApiV1UsersResponse>,
    QueryKey<Options<GetApiV1UsersData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiV1UsersData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiV1UsersData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV1Users({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiV1UsersInfiniteQueryKey(options),
    }
  );
};

/**
 * Create User
 *
 * This endpoint creates a new user.
 */
export const postApiV1UsersMutation = (
  options?: Partial<Options<PostApiV1UsersData>>
): UseMutationOptions<
  PostApiV1UsersResponse,
  PostApiV1UsersError,
  Options<PostApiV1UsersData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1UsersResponse,
    PostApiV1UsersError,
    Options<PostApiV1UsersData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiV1Users({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Assign Role
 *
 * This endpoint assigns a role to a user
 */
export const postApiV1UsersAssignRoleByUserIdByRoleIdMutation = (
  options?: Partial<Options<PostApiV1UsersAssignRoleByUserIdByRoleIdData>>
): UseMutationOptions<
  PostApiV1UsersAssignRoleByUserIdByRoleIdResponse,
  PostApiV1UsersAssignRoleByUserIdByRoleIdError,
  Options<PostApiV1UsersAssignRoleByUserIdByRoleIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1UsersAssignRoleByUserIdByRoleIdResponse,
    PostApiV1UsersAssignRoleByUserIdByRoleIdError,
    Options<PostApiV1UsersAssignRoleByUserIdByRoleIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiV1UsersAssignRoleByUserIdByRoleId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Unassign Role
 *
 * This endpoint unassigns a role from a user
 */
export const postApiV1UsersUnassignRoleByUserIdByRoleIdMutation = (
  options?: Partial<Options<PostApiV1UsersUnassignRoleByUserIdByRoleIdData>>
): UseMutationOptions<
  PostApiV1UsersUnassignRoleByUserIdByRoleIdResponse,
  PostApiV1UsersUnassignRoleByUserIdByRoleIdError,
  Options<PostApiV1UsersUnassignRoleByUserIdByRoleIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PostApiV1UsersUnassignRoleByUserIdByRoleIdResponse,
    PostApiV1UsersUnassignRoleByUserIdByRoleIdError,
    Options<PostApiV1UsersUnassignRoleByUserIdByRoleIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postApiV1UsersUnassignRoleByUserIdByRoleId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete User
 *
 * This endpoint deletes an existing user by their id.
 */
export const deleteApiV1UsersByIdMutation = (
  options?: Partial<Options<DeleteApiV1UsersByIdData>>
): UseMutationOptions<
  DeleteApiV1UsersByIdResponse,
  DeleteApiV1UsersByIdError,
  Options<DeleteApiV1UsersByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteApiV1UsersByIdResponse,
    DeleteApiV1UsersByIdError,
    Options<DeleteApiV1UsersByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteApiV1UsersById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1UsersByIdQueryKey = (
  options: Options<GetApiV1UsersByIdData>
) => createQueryKey('getApiV1UsersById', options);

/**
 * Get User
 *
 * This endpoint retrieves an existing user by their id.
 */
export const getApiV1UsersByIdOptions = (
  options: Options<GetApiV1UsersByIdData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1UsersById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1UsersByIdQueryKey(options),
  });
};

/**
 * Update User
 *
 * This endpoint updates an existing user by their id.
 */
export const putApiV1UsersByIdMutation = (
  options?: Partial<Options<PutApiV1UsersByIdData>>
): UseMutationOptions<
  PutApiV1UsersByIdResponse,
  PutApiV1UsersByIdError,
  Options<PutApiV1UsersByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PutApiV1UsersByIdResponse,
    PutApiV1UsersByIdError,
    Options<PutApiV1UsersByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await putApiV1UsersById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getApiV1UsersByUserIdListRolesQueryKey = (
  options: Options<GetApiV1UsersByUserIdListRolesData>
) => createQueryKey('getApiV1UsersByUserIdListRoles', options);

/**
 * List Roles
 *
 * This endpoint retrieves a list of role assigned to a user
 */
export const getApiV1UsersByUserIdListRolesOptions = (
  options: Options<GetApiV1UsersByUserIdListRolesData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getApiV1UsersByUserIdListRoles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getApiV1UsersByUserIdListRolesQueryKey(options),
  });
};

export const getApiV1UsersByUserIdListRolesInfiniteQueryKey = (
  options: Options<GetApiV1UsersByUserIdListRolesData>
): QueryKey<Options<GetApiV1UsersByUserIdListRolesData>> =>
  createQueryKey('getApiV1UsersByUserIdListRoles', options, true);

/**
 * List Roles
 *
 * This endpoint retrieves a list of role assigned to a user
 */
export const getApiV1UsersByUserIdListRolesInfiniteOptions = (
  options: Options<GetApiV1UsersByUserIdListRolesData>
) => {
  return infiniteQueryOptions<
    GetApiV1UsersByUserIdListRolesResponse,
    GetApiV1UsersByUserIdListRolesError,
    InfiniteData<GetApiV1UsersByUserIdListRolesResponse>,
    QueryKey<Options<GetApiV1UsersByUserIdListRolesData>>,
    | number
    | Pick<
        QueryKey<Options<GetApiV1UsersByUserIdListRolesData>>[0],
        'body' | 'headers' | 'path' | 'query'
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetApiV1UsersByUserIdListRolesData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  page: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getApiV1UsersByUserIdListRoles({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: getApiV1UsersByUserIdListRolesInfiniteQueryKey(options),
    }
  );
};
